### ISSUE TITLE
getting exception after applying amps.

### ISSUE THREAD

**Issue by monicakumari** [atolcd/alfresco-audit-share#18]
I have ceated a vanila installation and copied repo and share amps and applied them.
I am getting the following exception : 

`Caused by: org.alfresco.error.AlfrescoRuntimeException: 03130018 
Downgrading of modules is not supported.
Module 'com.atolcd.alfresco.auditshare-52X-repo' version 1.5.7 is currently installed and must be uninstalled before version 1.5.6 can be installed.
	at org.alfresco.error.AlfrescoRuntimeException.create(AlfrescoRuntimeException.java:52)
	at org.alfresco.repo.module.ModuleComponentHelper.startModule(ModuleComponentHelper.java:633)
	at org.alfresco.repo.module.ModuleComponentHelper.access$5(ModuleComponentHelper.java:530)
	at org.alfresco.repo.module.ModuleComponentHelper$1$1.execute(ModuleComponentHelper.java:263)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:352)
	at org.alfresco.repo.module.ModuleComponentHelper$1.doWork(ModuleComponentHelper.java:284)
	... 45 more
`

**Comment by bforest** [comment]
Hi,

Alfresco doesn't allow to downgrade modules (see https://issues.alfresco.com/jira/browse/ALF-20984).

Regards.

**Comment by monicakumari** [comment]
yaah.. thank you so much.. it was my mistake.. I have found it.. thanks or your help.
