### ISSUE TITLE
WebScriptException when searching with simple search 

### ISSUE THREAD

**Issue by patriciaZylk** [atolcd/alfresco-audit-share#2]
Hi,

I think we have found an issue when we search (simple search) documents that are stored in a site.

How to reproduce it: 
1. Go to repository 
2. Use simple search to search, for example "alfresco"

The following exception is shown in catalina.out:

```
 2014-02-11 09:16:36,004  ERROR [extensions.webscripts.AbstractRuntime] [http-8080-6] Exception from executeScript - redirecting to status template error: 01110003 [ShareStats-DbInsert] Error in executeImpl function
 org.springframework.extensions.webscripts.WebScriptException: 01110003 [ShareStats-DbInsert] Error in executeImpl function
	at com.atolcd.alfresco.web.scripts.shareStats.InsertAuditPost.executeImpl(InsertAuditPost.java:97)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
```

We have activated some debug traces and this is what we see in catalina.out:

```
2014-02-11 09:10:50,281  DEBUG [scripts.shareStats.InsertAuditPost] [http-8080-5] 01110357 Invalid node ref - does not contain forward slash: alfresco
 org.alfresco.error.AlfrescoRuntimeException: 01110357 Invalid node ref - does not contain forward slash: alfresco
	at org.alfresco.service.cmr.repository.NodeRef.<init>(NodeRef.java:105)
	at com.atolcd.alfresco.web.scripts.shareStats.InsertAuditPost.getSiteFromObject(InsertAuditPost.java:113)
	at com.atolcd.alfresco.web.scripts.shareStats.InsertAuditPost.executeImpl(InsertAuditPost.java:86)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
```

Hint: This behaviour is not happening when searching from a site, only when you search from the repository.

Affected versions: Alfresco Enterprise 4.1.5 EE (oracle 10 and mysql 5.5)

Regards,

Patricia Yagüe :: Zylk.net

**Comment by bforest** [comment]
Fixed in 1.4.4 version : https://labs.atolcd.com/attachments/download/282/auditshare-1.4.4.zip

Thanks.
