### ISSUE TITLE
Issue compiling the project for ACS 6.2.0

### ISSUE THREAD

**Issue by baazizaqimo** [atolcd/alfresco-audit-share#30]
Hello,

I have the following configuration:

> [makram@alfrescocentosvm ~]$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/maven/apache-maven-3.3.9
Java version: 11.0.7, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-11-openjdk-11.0.7.10-4.el7_8.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1127.13.1.el7.x86_64", arch: "amd64", family: "unix"

I'm trying to compile the project using the commande **mvn clean package** but I'm having the following issue

> [makram@alfrescocentosvm alfresco-audit-share]$ mvn clean package -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] AuditShare
[INFO] AuditShare - Repository
[INFO] AuditShare - Share
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AuditShare 1.6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ auditshare-62X ---
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building AuditShare - Repository 1.6.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.sun.xml.bind:jaxb-core:jar:2.2.11 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ auditshare-62X-repo ---
[INFO] Deleting /home/makram/Documents/ACS-SDK4/audit-share/alfresco-audit-share/module_alfresco/target
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ auditshare-62X-repo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /home/makram/Documents/ACS-SDK4/audit-share/alfresco-audit-share/module_alfresco/src/main/resources
[INFO] Copying 3 resources to alfresco/messages
[INFO] Copying 39 resources to alfresco/module/com.atolcd.alfresco.auditshare-62X-repo
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] AuditShare ......................................... SUCCESS [  0.080 s]
[INFO] AuditShare - Repository ............................ FAILURE [  3.311 s]
[INFO] AuditShare - Share ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.755 s
[INFO] Finished at: 2020-09-01T09:02:12+01:00
[INFO] Final Memory: 28M/140M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:resources (default-resources) on project auditshare-62X-repo: Input length = 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:resources (default-resources) on project auditshare-62X-repo: Input length = 1
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Input length = 1
        at org.apache.maven.plugins.resources.ResourcesMojo.execute(ResourcesMojo.java:362)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Input length = 1
        at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:113)
        at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:262)
        at org.apache.maven.plugins.resources.ResourcesMojo.execute(ResourcesMojo.java:356)
        ... 22 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
        at java.base/java.io.BufferedReader.read1(BufferedReader.java:210)
        at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.read(BufferedReader.java:182)
        at org.apache.maven.shared.filtering.BoundedReader.read(BoundedReader.java:85)
        at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:235)
        at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:197)
        at java.base/java.io.Reader.read(Reader.java:229)
        at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:199)
        at org.apache.maven.shared.utils.io.IOUtil.copy(IOUtil.java:181)
        at org.apache.maven.shared.utils.io.FileUtils.copyFile(FileUtils.java:1908)
        at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:98)
        ... 24 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :auditshare-62X-repo

Would you please help me to compile the project for ACS 6.2.0

Best Regards,
Makram

**Comment by sprouvez** [comment]
Hi Makram,

This problem provided by the maven resources plugin and some of properties file and other filtering feature. While waiting for the modification on our side you can force the value of the plugin like this in the pom.xml :

**Comment by baazizaqimo** [comment]
> Hi Makram,
> 
> This problem provided by the maven resources plugin and some of properties file and other filtering feature (encoding inside). While waiting for the modification on our side you can force the value of the plugin like this in the pom.xml :
> 
> ```
>   <build>
>     <pluginManagement>
>       <plugins>
>         <plugin>
>           <groupId>org.apache.maven.plugins</groupId>
>           <artifactId>maven-resources-plugin</artifactId>
>           <version>3.1.0</version>
>         </plugin>
>       </plugins>
>     </pluginManagement>
>   </build>
> ```
> 
> Stephane

Thank you so much Stephane, the issue is resolved and I was able to compile and deploy the project under ACS 6.2.1
