### ISSUE TITLE
Unable to start with Oracle database

### ISSUE THREAD

**Issue by omar-ounoughi** [atolcd/alfresco-audit-share#35]
Hello,

I installed the amps , after start we have this Warning : 

```log
WARN  [context.support.XmlWebApplicationContext] [main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.Bean          CreationException: Error creating bean with name 'com.atolcd.alfresco.scheduler.SiteVolumetryJobExecuter' defined in class path resource [alfresco/module/auditshare-repo/context/schedulers-context.xml]          : Cannot resolve reference to bean 'webscript.com.atolcd.alfresco.share-stats.insert-audit.post' while setting bean property 'wsInsertAudits'; nested exception is org.springframework.beans.factory.Bean          CreationException: Error creating bean with name 'webscript.com.atolcd.alfresco.share-stats.insert-audit.post' defined in URL [jar:file:/etc/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-          71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Cannot resolve reference to bean 'shareStatsQueriesSqlSessionClientTemplate' while setting bean property 'sqlSessionTemplate'; n          ested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareStatsQueriesSqlSessionClientTemplate' defined in URL [jar:file:/etc/opt/alfresco/tomcat/w          ebapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Cannot resolve reference to bean 'shareStatsAlfrescoSqlSessionClient' while setting const          ructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareStatsAlfrescoSqlSessionClient' defined in URL [jar:file:/etc/opt/alfres          co/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Invocation of init method failed; nested exception is org.springframework.core          .NestedIOException: Failed to parse config resource: class path resource [alfresco/module/auditshare-repo/ibatis/share-stats-SqlMapConfig.xml]; nested exception is org.apache.ibatis.builder.BuilderExce          ption: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/module/auditshare-repo/ibatis/#resource.dialect#/share-stats-select-Sq          lMap.xml
```

Followed with this Error : 

```log
2022-02-18 15:29:15,605  ERROR [web.context.ContextLoader] [main] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.atolcd.alfresco.scheduler.SiteVolumetryJobExecuter' defined in class path resource [alfresco/module/auditshar          e-repo/context/schedulers-context.xml]: Cannot resolve reference to bean 'webscript.com.atolcd.alfresco.share-stats.insert-audit.post' while setting bean property 'wsInsertAudits'; nested exception is           org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webscript.com.atolcd.alfresco.share-stats.insert-audit.post' defined in URL [jar:file:/etc/opt/alfresco/tomcat/we          bapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Cannot resolve reference to bean 'shareStatsQueriesSqlSessionClientTemplate' while setting           bean property 'sqlSessionTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareStatsQueriesSqlSessionClientTemplate' defined in UR          L [jar:file:/etc/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Cannot resolve reference to bean 'shareStatsAlfresc          oSqlSessionClient' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareStatsAlfrescoSqlSessionClient' de          fined in URL [jar:file:/etc/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Invocation of init method failed; nested           exception is org.springframework.core.NestedIOException: Failed to parse config resource: class path resource [alfresco/module/auditshare-repo/ibatis/share-stats-SqlMapConfig.xml]; nested exception is           org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/module/auditshare-repo/ibatis/#r          esource.dialect#/share-stats-select-SqlMap.xml
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1689)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1434)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:631)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1830)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:526)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:425)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webscript.com.atolcd.alfresco.share-stats.insert-audit.post' defined in URL [jar:file:/etc/opt/alfresc          o/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Cannot resolve reference to bean 'shareStatsQueriesSqlSessionClientTemplate' wh          ile setting bean property 'sqlSessionTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareStatsQueriesSqlSessionClientTemplate' de          fined in URL [jar:file:/etc/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Cannot resolve reference to bean 'shareS          tatsAlfrescoSqlSessionClient' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shareStatsAlfrescoSqlSessio          nClient' defined in URL [jar:file:/etc/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/auditshare-71X-repo-2.1.0.jar!/alfresco/module/auditshare-repo/module-context.xml]: Invocation of init method fai          led; nested exception is org.springframework.core.NestedIOException: Failed to parse config resource: class path resource [alfresco/module/auditshare-repo/ibatis/share-stats-SqlMapConfig.xml]; nested e          xception is org.apache.ibatis.builder.BuilderException: Error parsing SQL Mapper Configuration. Cause: org.apache.ibatis.builder.BuilderException: Failed to get resource: alfresco/module/auditshare-rep          o/ibatis/#resource.dialect#/share-stats-select-SqlMap.xml`
```

Instance Environment :

- Alfresco Enterprise 7.1.0 
- DB : Oracle 12.2
- AuditShare : 2.1.0

**Comment by jberthoux** [comment]
Hello,

Sorry for the delay, but a fix have been made for Oracle: https://github.com/atolcd/alfresco-audit-share/commit/60df8b387a5f93bdf47f4713acd442245a73183f

Regards,
Julien
