### ISSUE TITLE
Error When Calculating Volumerty 

### ISSUE THREAD

**Issue by massinissaBelaid** [atolcd/alfresco-audit-share#36]
An exception is throwing whend calculating volumerty for one Site, his weighs 400 GB.
The Error is a Solr Timout, it occurs in the ShareStatsget.DocsCmis(long).
I tried to increase the Solr timout, but it didn't work. 
I have try to run the same query for this site. and it work the seconde run, on the alfresco admin console (the second execution), I tried to do the query twice with a sleep in between, thinking that the result is saved in a cache, but still the same error.

have you ever had this problem?

thanks in advance,
Cordially.

**Comment by jberthoux** [comment]
Hi @massinissaBelaid,

firstly, thank you for downloading and use audit-share.
The Solr query is timed out because of the huge number of documents contained in the site. Do you know the number of documents of this site. Do you have some logs or error messages with this error?

Regards,
Julien

**Comment by massinissaBelaid** [comment]
Hi @jberthoux , 

thank you for your reply,
the site has more than 3000 documents.

Regards,
Massinissa.


StackTrace of the error:
```
org.alfresco.repo.search.QueryParserException: 00190055
        at org.alfresco.repo.search.impl.solr.SolrQueryHTTPClient.executeQuery(SolrQueryHTTPClient.java:594)
        at org.alfresco.repo.search.impl.solr.SolrQueryLanguage.executeQuery(SolrQueryLanguage.java:52)
        at org.alfresco.repo.search.impl.solr.DbOrIndexSwitchingQueryLanguage.executeQuery(DbOrIndexSwitchingQueryLanguage.java:216)
        at org.alfresco.repo.search.impl.solr.SolrSearchService.query(SolrSearchService.java:354)
        at org.alfresco.repo.search.SearcherComponent.query(SearcherComponent.java:84)
        at jdk.internal.reflect.GeneratedMethodAccessor753.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.alfresco.repo.management.subsystems.SubsystemProxyFactory$1.invoke(SubsystemProxyFactory.java:79)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy39.query(Unknown Source)
        at org.alfresco.repo.search.impl.SearchServiceSubSystemDelegator.query(SearchServiceSubSystemDelegator.java:133)
        at jdk.internal.reflect.GeneratedMethodAccessor753.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:80)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:53)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.alfresco.repo.audit.AuditMethodInterceptor.proceedWithAudit(AuditMethodInterceptor.java:256)
        at org.alfresco.repo.audit.AuditMethodInterceptor.proceed(AuditMethodInterceptor.java:216)
        at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:171)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy39.query(Unknown Source)
        at com.atolcd.alfresco.repo.jscript.ShareStats.getTotalSizeSite(ShareStats.java:259)
        at com.atolcd.alfresco.repo.jscript.ShareStats.getDocsCmis(ShareStats.java:230)
        at com.atolcd.alfresco.repo.jscript.ShareStats.insertVolumetryMulti(ShareStats.java:206)
        at com.atolcd.alfresco.scheduler.SiteVolumetryJobExecuter.execute(SiteVolumetryJobExecuter.java:73)
        at com.atolcd.alfresco.scheduler.SiteVolumetryJob$1.doWork(SiteVolumetryJob.java:48)
        at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:602)
        at com.atolcd.alfresco.scheduler.SiteVolumetryJob.executeJob(SiteVolumetryJob.java:45)
        at org.alfresco.schedule.ScheduledJobLockExecuter.execute(ScheduledJobLockExecuter.java:94)
        at org.alfresco.schedule.AbstractScheduledLockedJob.executeInternal(AbstractScheduledLockedJob.java:72)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
        at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
        at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
        at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
        at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
        at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at org.alfresco.repo.search.impl.solr.AbstractSolrQueryHTTPClient.postQuery(AbstractSolrQueryHTTPClient.java:95)

```

**Comment by jberthoux** [comment]
Hello,

2s is the defautl value, what is your new value?

Regards,
Julien

**Comment by massinissaBelaid** [comment]
Hi,

5000 for 5s,

Regards,
Massinissa

**Comment by jberthoux** [comment]
You can try to modify replication settings and give it a long connection time out value in your `solrconf.xml` file , located in `${SOLR_HOME}/workspace-SpacesStore/conf `and restart your server.

```
<requestHandler name="/replication" class="solr.ReplicationHandler" >

<str name="httpConnTimeout">5000</str>
<str name="httpReadTimeout">10000</str>
</requestHandler>
```

Regards,
Julien

**Comment by jberthoux** [comment]
You sould try with 20000 for `solr.http.socket.timeout`

Regards,
Julien

**Comment by massinissaBelaid** [comment]
thank you @jberthoux for your feedback

I put  yesterday the value to 15000,  it was taken into account after the night server restart, and the calculation of the stats was restored this morning.

Regards,
Massinissa

**Comment by jberthoux** [comment]
Hello,

Glade to read the issue is solved.

Regards,
Julien
